# This is a basic workflow to help you get started with Actions

name: Deploy to development server

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [development]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
            host: ${{vars.SSH_HOST}}
            username: ${{vars.SSH_USER}}
            password: ${{secrets.SSH_PASSPHRASE}}
            script: |
              cd /var/www/vhosts/oykos.me/${{vars.GIT_REPO}}.oykos.me
              [ -d "./github" ] && echo "Existing github directory" || mkdir github
              cd github
              rm -rf ./${{vars.GIT_REPO}}
              git clone -b development https://oykos-development-hub:${{secrets.GIT_ACCESS_TOKEN}}@github.com/oykos-development-hub/${{vars.GIT_REPO}}.git
              cd ./${{vars.GIT_REPO}}
              cp -R ./ ../../
              echo '<IfModule mod_headers.c>' > ../../.htaccess
              echo '    Header set Access-Control-Allow-Origin "https://sss-erp.oykos.me"' >> ../../.htaccess
              echo '</IfModule>' >> ../../.htaccess
              cp ../../.htaccess ../../dist
              cp ../../.htaccess ../../dist/assets
